name = "market-briefing-scheduler"
main = "scheduler.mjs"
compatibility_date = "2026-09-05"
workers_dev = false
preview_urls = false

[triggers]
crons = [
  "17,47 0-6 * * *",
  "17 7-23 * * *",
  "7 22 * * SUN-THU",
  "37 12 * * MON-FRI",
  "15,25,40 * * * *",
]
