"""Regenerate ``config/filing_ids.yaml`` — ticker → SEC CIK / DART corp_code.

    uv run python -m scripts.resolve_filing_ids

Rerun whenever ``config/watchlist.yaml`` gains or drops a ticker — nothing
does this automatically, so MANUAL-TASKS.md §2 names this as a follow-up step
to filling the watchlist.

Why this is safe to auto-write, unlike ``config/aliases.yaml``
----------------------------------------------------------------
CLAUDE.md forbids auto-generating or auto-extending ``aliases.yaml`` because a
wrong alias corrupts every downstream number silently. That risk does not
apply here: SEC's ``company_tickers.json`` and DART's ``corpCode.xml`` are
official, complete, exact-match government enumerations keyed by ticker/stock
code, not fuzzy judgment calls a human has to make. The risk here runs the
other way — a watchlist ticker with **no** match would make the filings
collectors silently skip it forever, with nothing in the report header to
say so. So this script fails loudly (non-zero exit, names every unmatched
ticker) rather than writing a partial file, and ``src.util.config.
load_filing_ids`` re-checks the same thing at load time in case the file is
ever hand-edited into staleness.

Sources
-------
- SEC: ``https://www.sec.gov/files/company_tickers.json`` — a flat JSON
  keyed by an arbitrary index, each value ``{"cik_str": int, "ticker": str,
  "title": str}``. Confirmed reachable with ``SEC_USER_AGENT`` live on
  2026-08-04 (MANUAL-TASKS.md §0) and again 2026-08-25 against this exact
  endpoint.
- DART: ``https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key=...`` — a zip
  containing one XML file, one ``<list>`` per company, fields ``corp_code``,
  ``corp_name``, ``corp_eng_name``, ``stock_code`` (empty for unlisted
  entities), ``modify_date``. 118,767 entries as of 2026-08-25. **The DART
  endpoint is slow** — observed roughly 10-15 KB/s for a ~30MB response,
  several minutes end to end — so this script's HTTP timeout is generous
  rather than tuned to a fast-path assumption.
"""

from __future__ import annotations

import io
import os
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree

import requests

from src.util.config import CONFIG_DIR, load_watchlist

SEC_TICKERS_URL = "https://www.sec.gov/files/company_tickers.json"
DART_CORP_CODE_URL = "https://opendart.fss.or.kr/api/corpCode.xml"

# Observed transfer rate on 2026-08-25 makes the DART call take several
# minutes; this is a generous ceiling, not a tuned expectation.
_DART_TIMEOUT_SECONDS = 300


def _sec_ticker_to_cik() -> dict[str, str]:
    agent = os.environ.get("SEC_USER_AGENT")
    if not agent:
        raise RuntimeError("SEC_USER_AGENT is not set")
    response = requests.get(SEC_TICKERS_URL, headers={"User-Agent": agent}, timeout=30)
    response.raise_for_status()
    data = response.json()
    return {row["ticker"]: str(row["cik_str"]).zfill(10) for row in data.values()}


def _dart_stock_to_corp_code() -> dict[str, str]:
    api_key = os.environ.get("DART_API_KEY")
    if not api_key:
        raise RuntimeError("DART_API_KEY is not set")
    response = requests.get(
        DART_CORP_CODE_URL, params={"crtfc_key": api_key}, timeout=_DART_TIMEOUT_SECONDS
    )
    response.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(response.content)) as archive:
        xml_bytes = archive.read("CORPCODE.xml")
    root = ElementTree.fromstring(xml_bytes)
    mapping: dict[str, str] = {}
    for entry in root:
        stock_code = (entry.findtext("stock_code") or "").strip()
        if stock_code:
            mapping[stock_code] = entry.findtext("corp_code")
    return mapping


def resolve(*, path: Path | None = None) -> Path:
    """Fetch both mappings, filter to the watchlist, write ``filing_ids.yaml``.

    Raises with every unmatched ticker named if either market has a gap —
    never writes a file that would leave a ticker's ``filing`` flag silently
    dead.
    """
    path = path or CONFIG_DIR / "filing_ids.yaml"

    kr_tickers = sorted(e.ticker for e in load_watchlist(market="KR"))
    us_tickers = sorted(e.ticker for e in load_watchlist(market="US"))

    dart_map = _dart_stock_to_corp_code()
    sec_map = _sec_ticker_to_cik()

    missing_kr = [t for t in kr_tickers if t not in dart_map]
    missing_us = [t for t in us_tickers if t not in sec_map]
    if missing_kr or missing_us:
        raise RuntimeError(
            "watchlist tickers with no filing-id match — "
            f"KR: {missing_kr or 'none'}, US: {missing_us or 'none'}"
        )

    lines = [
        "# Auto-generated by scripts/resolve_filing_ids.py — do not hand-edit.",
        "# Regenerate after any config/watchlist.yaml change (uv run python -m",
        "# scripts.resolve_filing_ids). Every value is an exact match against an",
        "# official government enumeration (SEC company_tickers.json / DART",
        "# corpCode.xml), not a hand judgment — see the module docstring for why",
        "# that makes auto-regeneration safe here but not for aliases.yaml.",
        "kr:",
    ]
    for ticker in kr_tickers:
        lines.append(f'  "{ticker}": {{corp_code: "{dart_map[ticker]}"}}')
    lines.append("us:")
    for ticker in us_tickers:
        lines.append(f'  "{ticker}": {{cik: "{sec_map[ticker]}"}}')
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    del argv
    try:
        path = resolve()
    except RuntimeError as exc:
        print(f"resolve_filing_ids failed: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
